version: 2
jobs:
  lint:
    docker:
      - image: hadolint/hadolint:v1.17.2-debian
    steps:
      - checkout
      - run:
          name: Lint dockerfile
          command: ./scripts/lint.sh
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t zenika/terraform-azure-cli:latest .
  build-tag:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t zenika/terraform-azure-cli:$CIRCLE_TAG .
  publish-latest:
    environment:
      IMAGE_NAME: building-on-ci
    context: docker-hub
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
            docker push zenika/terraform-azure-cli:latest
            docker push zenika/terraform-azure-cli:$CIRCLE_TAG
workflows:
  version: 2
  test-and-build:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - build-tag:
          requires:
            - lint
          filters:
            tags:
              only: /[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-tag:
          requires:
            - build
            - build-tag
          filters:
            tags:
              only: /[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
