name: build

# trigger on any push
# but not on master or tag
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
      - "!master"

env:
  ORGANIZATION: "zenika"
  IMAGE_NAME: "terraform-azure-cli"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Save branch name as env var
        run: echo "::set-env name=BRANCH::${GITHUB_REF##*/}"

      - name: Build image
        run: docker image build . --file Dockerfile --tag $ORGANIZATION/$IMAGE_NAME:$BRANCH

      - name: Save image
        run: docker image save -o $IMAGE_NAME-$BRANCH.tar $ORGANIZATION/$IMAGE_NAME:$BRANCH

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.BRANCH }}
          path: ${{ env.IMAGE_NAME }}-${{ env.BRANCH }}.tar
