name: lint-dockerfile

# trigger on any Dockerfile modification
on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/lint-dockerfile.yml"

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: "Dockerfile"
          config: "hadolint.yaml"
