name: release

# trigger on tag
on:
  push:
    tags:
      - "*.*"

env:
  ORGANIZATION: "zenika"
  IMAGE_NAME: "terraform-azure-cli"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build_push_release:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        versions:
          - { tf_version: "0.12.24", awscli_version: "2.5.1" }

    env:
      TF_VERSION: ${{ matrix.versions.tf_version }}
      AWS_CLI_VERSIOIN: ${{ matrix.versions.awscli_version }}
      IMAGE_TAG: "tf${{ matrix.versions.tf_version }}-azcli${{ matrix.versions.awscli_version }}"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get release tag and save in env var
        run: echo "::set-env name=RELEASE_TAG::${GITHUB_REF##*/}"

      - name: Build image
        run: docker image build . --file Dockerfile --build-arg TERRAFORM_VERSION=$TF_VERSION --build-arg AWS_CLI_VERSION=$AWS_CLI_VERSIOIN --tag $ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG-$IMAGE_TAG

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to registry
        run: docker push $ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG-$IMAGE_TAG

      - name: Save image
        run: docker image save -o $IMAGE_NAME-$RELEASE_TAG-$IMAGE_TAG.tar $ORGANIZATION/$IMAGE_NAME:r$RELEASE_TAG-$IMAGE_TAG

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.RELEASE_TAG }}-${{ env.IMAGE_TAG }}
          path: ${{ env.IMAGE_NAME }}-${{ env.RELEASE_TAG }}-${{ env.IMAGE_TAG }}.tar
